vich_uploader:
    db_driver: orm

    mappings:
        plannings_image:
            uri_prefix: /image/plannings
            upload_destination: '%kernel.project_dir%/public/images/plannings'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
